version: "3.5"
services:
  mongo:
    image: mongo:5.0
    container_name: teamj-mongo
    hostname: mongo
    command: --syslog

  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: teamjrabbitmq
    


  customerservice:
    image: teamj-soa-customer-service
    container_name: customerservicehost
    depends_on:
      - rabbitmq
      - mongo
    expose:
      - "8080"
    environment:
      - RABBIT_HOST=teamjrabbitmq
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=27017
      - PLAY_MODE=DEMO
      - SCHEDULING_ENABLED=false
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB=OFF
      - ENERGY_MONITOR_URL=http://energymonitorservice:8081
      - ACCOUNTING_SERVICE_URL=http://accountinghost:5007
      - PORT=8080
  
  bankservice:
    image: teamj-soa-bankservice
    container_name: bankservicehost
    expose:
      - "5006"
    environment:
      - PORT=5006
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB=OFF

  accounting:
    image: teamj-soa-accounting
    container_name: accountinghost
    depends_on:
      - rabbitmq
      - mongo
    expose:
      - "5007"
    environment:
      - RABBIT_HOST=teamjrabbitmq
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=27017
      - PLAY_MODE=DEMO
      - SCHEDULING_ENABLED=false
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB=OFF
      - EXTERNAL_BANK_API=http://bankservicehost:5006
      - PORT=5007
      - MEASURES_MONITOR_URL=http://energymonitorservice:8081

  energymonitorservice:
    image: teamj-soa-energy-monitor-service
    container_name: energymonitorservice
    depends_on:
      - rabbitmq
      - mongo
    expose:
      - "8081"
    environment:
      - RABBIT_HOST=teamjrabbitmq
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=27017
      - PLAY_MODE=DEMO
      - SCHEDULING_ENABLED=false
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB=OFF
      - PORT=8081
      - ACCOUNTING_SERVICE_URL=http://accountinghost:5007

  testrunner:
    image: teamj-soa-us12-runner
    container_name: us12testrunnerhost
    depends_on:
      - rabbitmq
      - mongo
      - accounting
      - bankservice
      - customerservice
      - energymonitorservice
    environment:
      - API_CUSTOMERS_HOST=customerservicehost
      - API_CUSTOMERS_PORT=8080
      - BANK_SERVICE_HOST=bankservicehost
      - BANK_SERVICE_PORT=5006
      - ACCOUNTING_SERVICE_HOST=accountinghost
      - ACCOUNTING_SERVICE_PORT=5007
      - ENERGY_MONITOR_HOST=energymonitorservice
      - ENERGY_MONITOR_PORT=8081
