FROM openjdk:17-bullseye

#the bullseye is to have a debian distribution that has the apt-get command
RUN apt-get update
RUN apt-get install wait-for-it
 
# copy only the artifacts we need from the first stage and discard the rest
COPY ./target/smartrix-0.0.1-SNAPSHOT.jar smartrix.jar
COPY start.sh start.sh
RUN chmod +x start.sh



# set the startup command to execute the jar
ENTRYPOINT ["./start.sh"]

