version: "3.5"
services:
  mongo:
    image: mongo:5.0
    container_name: teamj-mongo
    hostname: mongo
    command: --syslog


  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: teamjrabbitmq


  energymonitorservice:
    image: teamj-soa-energy-monitor-service
    container_name: energymonitorservice
    depends_on:
      - rabbitmq
      - mongo
    expose:
      - "8081"
    environment:
      - RABBIT_HOST=teamjrabbitmq
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=27017
      - PLAY_MODE=DEMO
      - SCHEDULING_ENABLED=false
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB=OFF
      - PORT=8081





  customerservice:
    image: teamj-soa-customer-service
    container_name: customerservicehost
    depends_on:
      - rabbitmq
      - mongo
    expose:
      - "8080"
    environment:
      - RABBIT_HOST=teamjrabbitmq
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=27017
      - PLAY_MODE=DEMO
      - SCHEDULING_ENABLED=false
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB=OFF
      - ENERGY_MONITOR_URL=http://energymonitorservice:8081
      - ACCOUNTING_SERVICE_URL=http://accountinghost:5007
      - PORT=8080

  electricitymeterregister:
    image: teamj-soa-electric-metere-register-service
    container_name: localproductionmonitor
    restart: on-failure
    depends_on:
      - energymonitorservice
      - mongo
    expose:
      - "8083"
    environment:
      - ENERGY_MONITOR_URL=http://energymonitorservice:8081
      - RABBIT_HOST=teamjrabbitmq
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=27017
      - PLAY_MODE=DEMO
      - SCHEDULING_ENABLED=false
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB=OFF
      - PORT=8083


  testrunner:
    image: teamj-soa-us11-us14-runner
    container_name: us1114testrunnerhost
    depends_on:
      - energymonitorservice
      - electricitymeterregister
    environment:
      - API_CUSTOMERS_HOST=customerservicehost
      - API_CUSTOMERS_PORT=8080
      - ENERGY_MONITOR_HOST=energymonitorservice
      - ENERGY_MONITOR_PORT=8081
      - ENERGY_METER_REGISTER_HOST=localproductionmonitor
      - ENERGY_METER_REGISTER_PORT=8083


