FROM openjdk:17-bullseye
 
# copy only the artifacts we need from the first stage and discard the rest
COPY ./target/energysupplier-0.0.1-SNAPSHOT.jar ./energysupplier.jar
COPY start.sh .
RUN chmod +x start.sh

# set the startup command to execute the jar
ENTRYPOINT ["./start.sh"]

